### ISSUE TITLE
Contribute type definitions to Typings!?

### ISSUE THREAD

**Issue by GrayedFox** [rkavalap/NightWatchTest#1]
Hey there,

Been looking for type script definitions for Nightwatch for ages. Thank you.

Would you be so kind as to contribute it to [typings](https://github.com/typings/typings)? They have a public repository [here](https://github.com/typings/registry) which acts as a register for all public type definitions.

Cheers!!

**Comment by rkavalap** [comment]
@GrayedFox I can look into this.

**Comment by GrayedFox** [comment]
Thank you :smile_cat:

**Comment by The-DL** [comment]
Please do. Big help in WebStorm having these.

**Comment by GrayedFox** [comment]
They should sort of just be there. I opened a bug report about this on the
JetBrains forums too

Che Fisher

Quality Assurance Test Engineer @ Glispa GmbH
m: +49 176 4566 3935
e: che.fisher@gmail.com

**Comment by rkavalap** [comment]
@GrayedFox, @BigForNothing  I am closing this. I created a separate repo with the type definitions. It will be added to typings based on comment here.  https://github.com/typings/typings/issues/322#issuecomment-236328461

**Comment by GrayedFox** [comment]
Sorry for the noob question Rahul - could you walk me through the
implementation? Do I just do it with Typings? I had a crack at it a while
back using PhPStorm and after adding it as a specified library it still
didn't work. Filmed a bug report with them but will likely be some time
before it get's a fix!

**Comment by rkavalap** [comment]
@GrayedFox 
`typings install nightwatch` will install type definition under typings directory. You will reference the index.d.ts within your test files So if you consider NightwatchTest repo, I don't need typings folder to be checked-in. But rather I can just add the typings install in my gulpfile  before performing the transpile step.

**Comment by GrayedFox** [comment]
Awesome, going through the steps now. Cheers!
